### ISSUE TITLE
dont works

### ISSUE THREAD

**Issue by XD493** [sprxsh/krunkerhack#1]
.

**Comment by XD493** [comment]
when u copy app.asar and game.ob.js to the game, its just showing sprxsh github/com but hack dont work

**Comment by thebashfile** [comment]
Have you read the help.md? if so can you send me a video of the issue?
CCM: sprx
Discord: SQLFail#6868

Best Regards, SPRX

**Comment by thebashfile** [comment]
Hack has been patched for now, issue closed.
